"""Coverage ingestion, cleanup, and per-function range mapping.

This module is central to making coverage data usable for CRAP scoring.
It must be robust on Windows (case-insensitive paths, locked .coverage files)
and POSIX while preserving deterministic behavior and never inventing coverage
percentages.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import os
import shutil
import subprocess
import xml.etree.ElementTree as ET


@dataclass(slots=True)
class CoverageDatabase:
    """Line-hit database derived from a coverage report.

    The database is intentionally language-agnostic. Language adapters are
    responsible for producing trustworthy function ranges, and this class maps
    those ranges onto the coverage line hits emitted by coverage tools.

    Keys in line_hits_by_file are always repo-relative POSIX paths (via
    normalize_repo_path) but the original casing from the report is preserved.
    """

    line_hits_by_file: dict[str, dict[int, int]]

    def coverage_for(
        self,
        file_path: str,
        start_line: int,
        end_line: int,
        warnings: list[str] | None = None,
    ) -> tuple[str, float | None]:
        """Return a stable coverage state and percentage for a function range.

        Args:
            file_path: Repo-relative path (as produced by source discovery /
                language analyzers). This may have different casing than the
                keys stored from the coverage report.
            start_line: First line (inclusive) of the function.
            end_line: Last line (inclusive) of the function.
            warnings: Optional list to which a diagnostic warning will be
                appended when a case-insensitive fallback match is used.
                This warning flows into ScanReport.warnings.

        The lookup is exact first (fast path). If that misses, on Windows
        (and to improve robustness portably) we perform a case-folded search
        over stored keys. This fixes the common situation where source
        discovery sees "Src/Foo.py" (from FS) while the coverage report
        (XML "filename=" or lcov "SF:") contains "src/foo.py".

        When a fallback is used we record a warning so the behavior remains
        auditable (never silent magic).

        Returns:
            ("measured", percent) or ("indeterminate", None). We never invent
            a percentage when the file or range is unknown.
        """
        lines = self.line_hits_by_file.get(file_path)
        if not lines:
            # Case-folded lookup fallback (addresses R1 / phase1-r1).
            # normalize_repo_path always emits / and keeps the casing it saw,
            # so dict keys carry the report's casing while row.file_path
            # carries the casing from discover_source_files (Path.resolve()).
            # A direct .get fails across case-only differences on win32 and
            # sometimes on macOS or when reports are generated by other tools.
            #
            # We always attempt the fallback (not strictly guarded to nt only)
            # so:
            #   * the behavior is improved on POSIX when a mismatch happens
            #     to occur (with an explicit warning)
            #   * unit tests are portable across the CI matrix (linux + win)
            # The warning makes the heuristic visible and the result
            # deterministic/auditable.
            folded = file_path.casefold()
            for k, v in self.line_hits_by_file.items():
                if k.casefold() == folded:
                    lines = v
                    if warnings is not None:
                        warnings.append(
                            "Case-insensitive coverage path match used: "
                            f"queried {file_path!r} against report key {k!r}. "
                            "This is normal on Windows (and harmless on POSIX); "
                            "coverage data was successfully mapped."
                        )
                    break
            if not lines:
                return ("indeterminate", None)

        relevant = [hits for line, hits in lines.items() if start_line <= line <= end_line]
        if not relevant:
            return ("indeterminate", None)

        covered = sum(1 for hits in relevant if hits > 0)
        percent = (covered / len(relevant)) * 100.0
        return ("measured", percent)


def normalize_repo_path(path: str | Path, root: Path) -> str:
    """Normalize any path into a repo-relative POSIX path when possible."""

    candidate = Path(path)
    if not candidate.is_absolute():
        candidate = root / candidate
    try:
        return candidate.resolve().relative_to(root.resolve()).as_posix()
    except ValueError:
        return candidate.resolve().as_posix()


def _parse_coverage_xml(report_path: Path, root: Path) -> CoverageDatabase:
    """Read ``coverage.py`` XML into a line-hit database."""

    tree = ET.parse(report_path)
    line_hits_by_file: dict[str, dict[int, int]] = {}

    for class_node in tree.findall(".//class"):
        filename = class_node.attrib.get("filename")
        if not filename:
            continue
        normalized = normalize_repo_path(filename, root)
        bucket = line_hits_by_file.setdefault(normalized, {})
        for line_node in class_node.findall("./lines/line"):
            line_number = line_node.attrib.get("number")
            hits = line_node.attrib.get("hits")
            if not line_number or not hits:
                continue
            bucket[int(line_number)] = int(hits)

    return CoverageDatabase(line_hits_by_file=line_hits_by_file)


def _parse_lcov(report_path: Path, root: Path) -> CoverageDatabase:
    """Read LCOV into a line-hit database for JS/TS and Rust workflows."""

    line_hits_by_file: dict[str, dict[int, int]] = {}
    current_file: str | None = None

    for raw_line in report_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if line.startswith("SF:"):
            current_file = normalize_repo_path(line[3:], root)
            line_hits_by_file.setdefault(current_file, {})
            continue
        if line.startswith("DA:") and current_file:
            line_number, hits = line[3:].split(",", maxsplit=1)
            line_hits_by_file[current_file][int(line_number)] = int(hits)
            continue
        if line == "end_of_record":
            current_file = None

    return CoverageDatabase(line_hits_by_file=line_hits_by_file)


def load_coverage_database(
    root: Path,
    report_path: str | None,
    report_format: str | None,
) -> CoverageDatabase | None:
    """Load a coverage database when the configured report exists.

    Unknown or missing coverage reports are treated as absent instead of causing
    the whole scan to fail because agents still benefit from complexity-only
    guidance with an explicit indeterminate coverage warning.
    """

    if not report_path or not report_format:
        return None

    candidate = Path(report_path)
    resolved = candidate if candidate.is_absolute() else root / candidate
    if not resolved.exists():
        return None

    normalized_format = report_format.strip().lower()
    if normalized_format == "coverage.py-xml":
        return _parse_coverage_xml(resolved, root)
    if normalized_format == "lcov":
        return _parse_lcov(resolved, root)
    raise ValueError(f"Unsupported coverage format: {report_format}")


def cleanup_artifacts(root: Path, artifact_paths: list[str]) -> list[str]:
    """Delete configured stale artifacts before running coverage.

    Hardened for Windows (Issue E1 / phase1-e1):
    - Uses shutil.rmtree for directories (the recursive walk+rmdir pattern
      is error-prone on Windows with readonly bits, in-use files such as
      .coverage left by pytest-cov, hidden files, etc.).
    - Individual operations and the rmtree are wrapped so that a single
      stubborn artifact (very common for the .coverage file on Windows)
      never aborts the overall scan.
    - Problems are returned as warning strings instead of being raised.
      Callers (cli._scan) extend the warnings list so they appear in the
      final ScanReport.warnings and are printed.

    The return value is always a (possibly empty) list of warning messages.
    """

    warnings: list[str] = []
    for artifact in artifact_paths:
        candidate = Path(artifact)
        resolved = candidate if candidate.is_absolute() else root / candidate
        if not resolved.exists():
            continue
        if resolved.is_dir():
            # Use a local onerror so we can collect per-path issues without
            # letting rmtree raise and abort the scan. rmtree will continue
            # after calling onerror for each failure.
            def _onerror(func, path, exc_info):  # type: ignore[no-untyped-def]
                err = exc_info[1] if exc_info else "unknown error"
                warnings.append(
                    f"cleanup: could not remove {path} "
                    f"(via {getattr(func, '__name__', func)}): {err}"
                )

            try:
                shutil.rmtree(resolved, ignore_errors=False, onerror=_onerror)
            except Exception as exc:
                # Belt-and-suspenders: if something prevents even the onerror path
                warnings.append(f"cleanup: rmtree failed for directory {resolved}: {exc}")
        else:
            # Regular file (or symlink etc.) — wrap the unlink.
            try:
                resolved.unlink(missing_ok=True)
            except Exception as exc:
                warnings.append(f"cleanup: could not remove file artifact {resolved}: {exc}")
    return warnings


def run_coverage_command(root: Path, command: str) -> tuple[bool, str]:
    """Run a configured coverage command.

    Always uses shell=True and the exact string supplied by the user in
    their repo-local .crap4code.toml (this is the documented UX contract).

    IMPORTANT Windows note (S1/S2 / phase1-s1):
    On Windows, subprocess with shell=True uses the value of %ComSpec%
    (normally C:\\Windows\\System32\\cmd.exe) regardless of whether the user
    launched Python from PowerShell (pwsh), Git Bash, or VS Code's terminal.
    The && chaining in the default sample config works under cmd.exe.

    Returns:
        A tuple of ``(success, detail)``. On success, detail is the captured
        stdout+stderr. On failure (or spawn error) the detail is a multi-line
        diagnostic block that includes:
          - the platform shell that was used (ComSpec / SHELL values)
          - the exact command string
          - the cwd
          - the return code (when the subprocess object existed)
        This is printed (prefixed) by the CLI caller so Windows users have
        actionable information instead of a bare failure.

    The caller in cli.py also prints an extra actionable hint about using
    shell-agnostic forms (python -m ...) or explicit pwsh -Command wrappers
    when the user's command contains pwsh-specific syntax.
    """

    # Capture the shell identifiers for diagnostics. These are what the
    # platform's shell=True will actually invoke.
    comspec = os.environ.get("ComSpec")
    shell_env = os.environ.get("SHELL")
    shell_desc = comspec if (os.name == "nt" and comspec) else (shell_env or ("cmd.exe" if os.name == "nt" else "sh"))

    try:
        completed = subprocess.run(
            command,
            cwd=root,
            shell=True,
            check=False,
            capture_output=True,
            text=True,
            env=os.environ.copy(),
        )
    except OSError as exc:
        detail = (
            f"Platform shell: {shell_desc} "
            f"(ComSpec={comspec!r}, SHELL={shell_env!r})\n"
            f"Command: {command!r}\n"
            f"cwd: {root}\n"
            f"spawn error (OSError): {exc}\n"
            "Hint (Windows): coverage commands run under cmd.exe. "
            "Use 'python -m pytest ...' forms or 'pwsh -Command \"...\"' for pwsh syntax."
        )
        return (False, detail)

    output = "\n".join(part for part in (completed.stdout, completed.stderr) if part).strip()
    if completed.returncode == 0:
        return (True, output)

    # Failure case: return rich actionable diagnostics (S1/S2).
    detail = (
        f"Platform shell: {shell_desc} "
        f"(ComSpec={comspec!r}, SHELL={shell_env!r})\n"
        f"Command: {command!r}\n"
        f"cwd: {root}\n"
        f"returncode: {completed.returncode}\n"
        f"--- captured output (stdout + stderr) ---\n"
        f"{output or '(no output captured)'}\n"
        "Hint (Windows): This was executed as cmd.exe /c '<command>'. "
        "If your command uses PowerShell-specific syntax, rewrite it as "
        "pwsh -Command '...' or prefer python -m based commands that do not "
        "depend on shell features."
    )
    return (False, detail)
